// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/change-password": {
            "post": {
                "description": "Change user password using verification token obtained from OTP verification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Password Reset"
                ],
                "summary": "Change password with verification token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Verification token from OTP verification",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "New password data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_request.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password changed successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request data or token",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Invalid or expired verification token",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate user with email and password. Returns JWT token on successful authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_request.LoginUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Create a new user account with email verification. Returns JWT token and sends verification email.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register new user",
                "parameters": [
                    {
                        "description": "User registration data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_request.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request data or user already exists",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/request-change-password": {
            "post": {
                "description": "Send OTP code to user's email for password reset. OTP expires in 24 hours.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Password Reset"
                ],
                "summary": "Request password reset",
                "parameters": [
                    {
                        "description": "Email address for password reset",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_request.RequestChangePasswordOtpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password reset email sent successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Email not found",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/resend-verification": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Resend 6-digit OTP verification code to user's email address. Rate limited to once per minute to prevent spam. User must be authenticated to use this endpoint.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email Verification"
                ],
                "summary": "Resend email verification code",
                "responses": {
                    "200": {
                        "description": "Verification email sent successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Rate limit exceeded or email already verified",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests - rate limited",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/verification-status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the current email verification status for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email Verification"
                ],
                "summary": "Check email verification status",
                "responses": {
                    "200": {
                        "description": "Verification status retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/verify-email": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Verify user's email address using 6-digit OTP code received via email. User must be authenticated to use this endpoint.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email Verification"
                ],
                "summary": "Verify email address with OTP",
                "parameters": [
                    {
                        "description": "OTP verification data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_request.OtpVerificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email verified successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request data or OTP",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/verify-otp-password-change": {
            "post": {
                "description": "Verify OTP code received via email and get verification token for password reset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Password Reset"
                ],
                "summary": "Verify OTP and get verification token",
                "parameters": [
                    {
                        "description": "Email and OTP verification data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_request.VerifyOTPAndEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP verified successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request data or OTP",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Email not found or OTP expired",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/budget": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve detailed budget information for authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budget Management"
                ],
                "summary": "Get user budget details",
                "responses": {
                    "200": {
                        "description": "Budget details retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Budget not found",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update existing budget for authenticated user with default (50-30-20) or custom allocation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budget Management"
                ],
                "summary": "Update user budget",
                "parameters": [
                    {
                        "description": "Budget data (custom percentages optional)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_request.BudgetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Budget updated successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Budget not found",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create budget for authenticated user with default (50-30-20) or custom allocation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budget Management"
                ],
                "summary": "Create user budget",
                "parameters": [
                    {
                        "description": "Budget data (custom percentages optional)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_request.BudgetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Budget created successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Budget already exists",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete the budget for authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budget Management"
                ],
                "summary": "Delete user budget",
                "responses": {
                    "200": {
                        "description": "Budget deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Budget not found",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/budget/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve detailed budget summary including allocation, usage, and remaining amounts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budget Management"
                ],
                "summary": "Get detailed budget summary with usage",
                "responses": {
                    "200": {
                        "description": "Budget summary retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Budget not found",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reports/period": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generate period report for user within date range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Period Report"
                ],
                "summary": "Create period report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/reports/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all period reports for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Period Report"
                ],
                "summary": "Get all user reports",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/reports/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get specific period report by report ID for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Period Report"
                ],
                "summary": "Get user report by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Report ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all transactions for the authenticated user including photos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction Management"
                ],
                "summary": "Get all user transactions",
                "responses": {
                    "200": {
                        "description": "Transactions retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new transaction for the authenticated user with optional photo upload",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction Management"
                ],
                "summary": "Create a new transaction",
                "parameters": [
                    {
                        "enum": [
                            "income",
                            "expense"
                        ],
                        "type": "string",
                        "description": "Transaction type",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Transaction amount (must be greater than 0)",
                        "name": "amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Transaction description",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Transaction date (YYYY-MM-DD format)",
                        "name": "date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "needs",
                            "wants",
                            "savings"
                        ],
                        "type": "string",
                        "description": "Budget category",
                        "name": "budget_category",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Transaction photo/receipt (max 5MB, jpg/png/gif/webp)",
                        "name": "photo",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Transaction created successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Category not found",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transactions/period": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve transactions grouped by specified period (daily, weekly, monthly)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction Management"
                ],
                "summary": "Get transactions by period",
                "parameters": [
                    {
                        "enum": [
                            "daily",
                            "weekly",
                            "monthly"
                        ],
                        "type": "string",
                        "description": "Period type",
                        "name": "period_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transactions by period retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transactions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a specific transaction by ID for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction Management"
                ],
                "summary": "Get transaction by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID (UUID format)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid transaction ID",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Transaction not found",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update transaction details for the authenticated user with optional photo upload",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction Management"
                ],
                "summary": "Update an existing transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID (UUID format)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "income",
                            "expense"
                        ],
                        "type": "string",
                        "description": "Transaction type",
                        "name": "type",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Transaction amount (must be greater than 0)",
                        "name": "amount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Transaction description",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Transaction date (YYYY-MM-DD format)",
                        "name": "date",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "needs",
                            "wants",
                            "savings"
                        ],
                        "type": "string",
                        "description": "Budget category",
                        "name": "budget_category",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Transaction photo/receipt (max 5MB, jpg/png/gif/webp)",
                        "name": "photo",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction updated successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Transaction not found",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a specific transaction for the authenticated user including its photo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction Management"
                ],
                "summary": "Delete a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID (UUID format)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid transaction ID",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Transaction not found",
                        "schema": {
                            "$ref": "#/definitions/gin-backend-app_internal_dto_common.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gin-backend-app_internal_dto_common.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Detailed error message"
                },
                "message": {
                    "type": "string",
                    "example": "Something went wrong"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "gin-backend-app_internal_dto_common.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Operation successful"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "gin-backend-app_internal_dto_request.BudgetRequest": {
            "type": "object",
            "required": [
                "weekly_income"
            ],
            "properties": {
                "needs_percent": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0,
                    "example": 20
                },
                "savings_percent": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0,
                    "example": 50
                },
                "wants_percent": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0,
                    "example": 30
                },
                "weekly_income": {
                    "type": "number",
                    "example": 1000000
                }
            }
        },
        "gin-backend-app_internal_dto_request.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "confirm_password",
                "new_password"
            ],
            "properties": {
                "confirm_password": {
                    "type": "string",
                    "example": "MyNewSecurePass123!"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "MyNewSecurePass123!"
                }
            }
        },
        "gin-backend-app_internal_dto_request.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "john_doe"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "MySecurePass123!"
                }
            }
        },
        "gin-backend-app_internal_dto_request.LoginUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "MySecurePass123!"
                }
            }
        },
        "gin-backend-app_internal_dto_request.OtpVerificationRequest": {
            "type": "object",
            "required": [
                "token_otp"
            ],
            "properties": {
                "token_otp": {
                    "type": "string",
                    "example": "ABCD12"
                }
            }
        },
        "gin-backend-app_internal_dto_request.RequestChangePasswordOtpRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                }
            }
        },
        "gin-backend-app_internal_dto_request.VerifyOTPAndEmailRequest": {
            "type": "object",
            "required": [
                "email",
                "token_otp"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "token_otp": {
                    "type": "string",
                    "example": "ABCD12"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Traspac Backend API",
	Description:      "Backend API for Traspac Competition",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
